version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-app


  api-gateway:
    build: ./api-gateway
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - my-app

networks:
  my-app:




