version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-app
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-gateway:
    build: ./api-gateway
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - my-app

  transcribe-service:
    build: ./transcribe
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    env_file:
      - .env
    networks:
      - my-app


networks:
  my-app:
